# Numpy Practice
- Author: Alireza Dirafzoon
- Contributions are welcome :) 

In [2]:
import numpy as np 

In [2]:
### array()
a = [1, 2, 3]
x = np.array(a) 
x = np.asarray(a)
x

array([1, 2, 3])

In [3]:
x.tolist()

[1, 2, 3]

In [4]:
x.astype(np.float32)

array([1., 2., 3.], dtype=float32)

In [6]:
### arange()
np.arange(3) 
np.arange(0,7,2) 
np.arange(3, -1, -1)

array([3, 2, 1, 0])

In [7]:
### zeros, ones, eye, linspace
np.zeros(3) 
np.zeros((3,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(3)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.linspace(0,10,3) # 3 points, from 0 to 10, inclusive 
np.linspace(0,7,3) 

array([0. , 3.5, 7. ])

In [15]:
### np.random

# random.rand(): uniform distr over [0, 1)
np.random.rand()   
np.random.rand(2)
np.random.rand(2,3)

array([[0.7771434 , 0.08427174, 0.84780602],
       [0.6069425 , 0.72381233, 0.54255502]])

In [16]:
# random.randn(): normal distr.
np.random.randn(2,3)

array([[ 2.2473354 , -1.27775236, -0.70635289],
       [-1.56768889,  0.33955847, -0.16860601]])

In [32]:
# random.randint: int in [low,high) / [0, high)
np.random.randint(1,4)
np.random.randint(1,4, (2,2))

array([[2, 3],
       [3, 1]])

In [34]:
np.random.randint(4)

3

In [124]:
## array methods 

### reshape
a = np.arange(1,7)
a = a.reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
### max, min, atgmax, argmin 
a.max(axis = 0)

array([4, 5, 6])

In [126]:
a.argmax(axis=0)

array([1, 1, 1])

In [127]:
a.max(axis = 1)

array([3, 6])

In [128]:
a.max()

6

In [129]:
a.argmax()

5

In [130]:
### shape and dtype 
a.shape

(2, 3)

In [131]:
a.dtype

dtype('int64')

In [132]:
a.nbytes

48

In [3]:
### 2D array/matrix 
m = np.arange(12).reshape(3,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
m.mean(axis=0)

array([4., 5., 6., 7.])

In [139]:
m.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [140]:
m.T # or m.transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [142]:
m.reshape((-1,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [141]:
m.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
m.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
## indexing and selection

In [6]:
print(m[1][2])
print(m[1,2])
print(m[1,:])

6
6
[4 5 6 7]


In [8]:
## boradcasting
a = np.zeros(10)
a[5:8] = 5 # note we can't do this with list 
a

array([0., 0., 0., 0., 0., 5., 5., 5., 0., 0.])

In [9]:
suba = a[:3]
suba[:] = 2
suba

array([2., 2., 2.])

In [135]:
a # note that suba is not a copy, just points to a slice of a

array([2., 2., 2., 0., 0., 5., 5., 5., 0., 0.])

In [136]:
suba = np.copy(a[:3])
suba

array([2., 2., 2.])

In [101]:
m = np.zeros((4,4))
m[1] = 2
m

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [104]:
# fancy indexing
m[[1,3]]

array([[2., 2., 2., 2.],
       [0., 0., 0., 0.]])

In [153]:
## selection 
a = np.arange(4)
a > 2 # note we can't do this with list 

array([False, False, False,  True])

In [156]:
(a == 2).astype(np.int16).sum()

1

In [154]:
a.nonzero()

(array([1, 2, 3]),)

In [108]:
## Operations

In [159]:
a, b = np.arange(0,3), np.arange(3,6)
a + b
a - b 
a * b # element-wise 
a/b # element-wise 

array([0.  , 0.25, 0.4 ])

In [114]:
np.multiply(a,b) # element-wise 

array([ 0,  4, 10])

In [163]:
# dot product of arrays
np.dot(a,b)

14

In [164]:
# cross product 
np.cross(a,b)

array([-3,  6, -3])

In [162]:
# matrix multiplication
np.matmul(a,b.T)

14

In [177]:
a = np.arange(9).reshape((3,3)) #2D
b = np.array([0,1,0]) # 1D
print(a,b) 
np.matmul(a,b) # 2D * 1D -> broadcasts the 1D array, treating it as a col 

[[0 1 2]
 [3 4 5]
 [6 7 8]] [0 1 0]


array([3, 4, 5])

In [120]:
np.power(a,2) # element-wise 
np.power(a,b) # element-wise 
np.mod(a,b)

array([0, 1, 2])

In [178]:
np.sqrt(a)
np.exp(a)
np.sin(a)
np.log(a)

/Users/alirezadirafzoon/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


array([[      -inf, 0.        , 0.69314718],
       [1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154]])

In [58]:
## Kmeans 

In [67]:
x1 = np.add(np.random.randn(10,2), 5)
x2 = np.add(np.random.randn(10,2), -5)
X = np.concatenate([x1,x2], axis=0)
mu, clusters = kmeans(X,2)

TypeError: Population must be a sequence or set.  For dicts, use list(d).

[[4.8649386655349955, 3.9952475402226817],
 [5.498489206113001, 5.069951322563478],
 [4.929449898684354, 5.719151512307626],
 [4.595440437145644, 4.810271477510138],
 [5.285073437207049, 5.922053828848186],
 [3.2378112256065865, 4.595935658934975],
 [3.8231073755832887, 6.144586325794659],
 [4.1009988278675245, 6.559105478655928],
 [3.9976386132206, 4.424471531025596],
 [4.691876028371731, 5.345908717367563],
 [-5.720985281350966, -5.68922383985498],
 [-5.4201288230000815, -4.431411907717413],
 [-3.6983426126902725, -4.636565625778152],
 [-5.342010805119905, -6.095419133835849],
 [-4.2666049359220235, -3.284073438471302],
 [-6.469221214094414, -7.369070651238069],
 [-3.284553291631532, -5.672466183383029],
 [-3.4845642662555996, -5.40312458836927],
 [-5.6863731385517005, -5.30056130289524],
 [-5.194321373602274, -5.935463756358125]]

In [18]:
import random
def dist():
    pass 
def assign_clusters(X, mu):
    
def kmeans(X,k):
    mu = random.sample(X,k)
    it = 1 
    max_it  = 100
    while it < max_it: 
        # assign clusters to centers 
        clusters = assign_clusters(X, mu)
        # calculate new centers 
        mu = calculate_centers(mu, clusters)
    return mu, clusters

array([[ 4.61084009,  3.81951528,  4.80554869,  4.89529018,  4.32093641,
         4.23753206,  2.72005748,  6.7060486 ,  4.02801539,  4.04573508,
        -6.07068165, -7.1437371 , -6.49431954, -4.90412879, -5.25460504,
        -3.86646858, -6.98290866, -4.82434449, -6.14940609, -6.55090156],
       [ 4.79319455,  4.07846865,  6.5072268 ,  4.9865201 ,  4.66317278,
         2.8773762 ,  3.67165213,  4.9436099 ,  3.93374775,  1.65634458,
        -5.16876443, -5.99996567, -4.70701913, -5.61868297, -5.08846978,
        -6.31017567, -3.46475003, -4.53046633, -4.35615641, -7.20485829]])

In [40]:
mu = np.random.rand(5,2)
x = np.random.rand(2)

In [41]:
[-mu[i[0]] for i in enumerate(mu)]

[array([-0.722217  , -0.95781472]),
 array([-0.43986246, -0.58463802]),
 array([-0.16399214, -0.27117604]),
 array([-0.88255848, -0.98718324]),
 array([-0.53056903, -0.60690576])]

In [48]:
for i, mu_i in enumerate(mu):
    print(min(i, np.linalg.norm(x - mu_i), key=lambda x:x[1]))

TypeError: 'int' object is not subscriptable

0 [1, 2, 3]
1 [4, 5, 6]
